version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wee-beastie-app
    container_name: wee-beastie-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:Cx2WWB2KRXadyXIAGdTyRXMHJMlLACKJD/DJWM4LDE0=
      - DB_HOST=db
      - DB_DATABASE=wee_beastie
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - db
    ports:
      - "9000:9000"

  db:
    image: mysql:8.0
    container_name: wee-beastie-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wee_beastie
      MYSQL_ROOT_PASSWORD: deew4eaYea8Viep0!!
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: wee-beastie-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  dbdata: